# Generated by Django 3.1 on 2020-08-31 08:45

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import wms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Magyarország', max_length=122)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=122)),
                ('district', models.IntegerField(default=None)),
                ('street_name', models.CharField(max_length=122)),
                ('street_type', models.CharField(max_length=122)),
                ('house_number', models.IntegerField()),
                ('tax_number', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('barcode', models.CharField(max_length=254, validators=[wms.models.Product.only_digit])),
                ('item_number', models.CharField(max_length=122)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=254)),
                ('notification_num', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('size', django_mysql.models.EnumField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XXL', 'Very large')], default='S')),
            ],
        ),
        migrations.CreateModel(
            name='RackLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location', models.CharField(max_length=122)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('section', models.IntegerField()),
                ('barcode', models.CharField(max_length=122)),
                ('fullness_percentage', models.PositiveIntegerField(default=0)),
                ('is_putaway', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('url', models.URLField(unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(editable=False, max_length=122, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_mysql.models.EnumField(choices=[('TK_OV', 'Taken over'), ('SHP', 'On shipping'), ('STD', 'Stored')], default='SHP')),
                ('comment', models.CharField(default='', max_length=254)),
                ('webshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.webshop')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(editable=False)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.receivingpackage')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLoction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product')),
                ('rack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.racklocation')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='webshop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.webshop'),
        ),
    ]
