# Generated by Django 3.1 on 2020-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webshop',
            name='tpye',
            field=models.CharField(default='UKNOWN', max_length=122),
        ),
    ]
