# Generated by Django 3.1 on 2020-08-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivingitems',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='receivingpackage',
            name='track_id',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
