# Generated by Django 3.1 on 2020-08-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_webshop_tpye'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Magyarország', max_length=122)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=122)),
                ('district', models.IntegerField(default=None)),
                ('street_name', models.CharField(max_length=122)),
                ('street_type', models.CharField(max_length=122)),
                ('house_number', models.IntegerField()),
                ('tax_number', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('barcode', models.CharField(max_length=254, unique=True)),
                ('item_number', models.CharField(max_length=122, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=254)),
                ('notification_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RackLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location', models.CharField(max_length=122)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('section', models.IntegerField()),
                ('barcode', models.CharField(max_length=122)),
                ('fullness_percentage', models.IntegerField(default=0)),
                ('is_putaway', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='webshop',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='webshop',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='ProductLoction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product')),
                ('rack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.racklocation')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='webshopId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.webshop'),
        ),
    ]
