# Generated by Django 3.1 on 2020-08-31 14:10

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20200831_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racklocation',
            name='is_putaway',
        ),
        migrations.AddField(
            model_name='racklocation',
            name='rack_type',
            field=django_mysql.models.EnumField(choices=[('TK_RK', 'Take-in rack'), ('RK', 'Rack'), ('PT_RK', 'Putaway rack'), ('PK_RK', 'Picking rack')], default='RK'),
        ),
    ]
