# Generated by Django 3.1 on 2020-09-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_auto_20200831_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productloction',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productloction',
            old_name='rack_id',
            new_name='rack',
        ),
        migrations.AddField(
            model_name='racklocation',
            name='products',
            field=models.ManyToManyField(through='wms.ProductLoction', to='wms.Product'),
        ),
    ]
