# Generated by Django 3.1 on 2020-08-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_auto_20200820_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webshop',
            name='tpye',
        ),
    ]
