# Generated by Django 3.1 on 2020-08-24 12:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_remove_webshop_tpye'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=django_mysql.models.EnumField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XXL', 'Very large')], default='S'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='notification_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racklocation',
            name='fullness_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
