# Generated by Django 3.1 on 2020-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_auto_20200901_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racklocation',
            name='barcode',
            field=models.CharField(max_length=122, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='racklocation',
            unique_together={('row', 'column', 'floor', 'section')},
        ),
    ]
