# Generated by Django 3.1.1 on 2020-09-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_auto_20200903_0756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productloction',
            unique_together={('product', 'rack')},
        ),
    ]
