# Generated by Django 3.1 on 2020-08-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_auto_20200824_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='webshopId',
            new_name='webshop_id',
        ),
    ]
