# Generated by Django 3.1 on 2020-08-24 13:25

from django.db import migrations, models
import wms.models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20200824_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=254, validators=[wms.models.Product.only_digit]),
        ),
    ]
