# Generated by Django 3.1.1 on 2020-09-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20200911_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLoction',
            new_name='ProductLocation',
        ),
    ]
