# Generated by Django 3.1 on 2020-08-25 16:42

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_auto_20200824_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productloction',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ReceivingPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=56, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_mysql.models.EnumField(choices=[('TK_OV', 'Taken over'), ('SHP', 'On shipping'), ('STD', 'Stored')], default='SHP')),
                ('comment', models.CharField(default='', max_length=254)),
                ('webshop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.webshop')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.receivingpackage')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product')),
            ],
        ),
    ]
