# Generated by Django 3.1 on 2020-08-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_auto_20200825_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingitems',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='webshop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.webshop'),
        ),
        migrations.AlterField(
            model_name='receivingitems',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms.receivingpackage'),
        ),
        migrations.AlterField(
            model_name='receivingitems',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wms.product'),
        ),
        migrations.AlterField(
            model_name='receivingpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receivingpackage',
            name='track_id',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
