# Generated by Django 3.1 on 2020-08-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_auto_20200828_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingitems',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receivingitems',
            name='quantity',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='receivingpackage',
            name='track_id',
            field=models.CharField(editable=False, max_length=122, unique=True),
        ),
        migrations.AlterField(
            model_name='receivingpackage',
            name='webshop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.webshop'),
        ),
    ]
